#import "@local/lecture:0.1.0" : *

#set page(
  numbering: "1",
  supplement: [p.],
  number-align: right,
  header: [
    #set text(8pt)
    #smallcaps[Self Reading Notes]
    #h(1fr) _Groups and Symmetry (M. A. Armstrong)_
  ],
)

= Groups and Symmetry

#def(title: "Group", [
  A group $(G, binop)$ where $G$ is a set and $binop$ satisfies
  1. Associative, $(x binop y) binop z = x binop (y binop z)$
  2. Identity, there exist an $e in G$ where $x e = x = e x$
  3. Inverse, each element $x$ has an inverse, $x x^(-1) = e = x^(-1) x$

  A group is *abelian* if $binop$ is commutative.
])

- $whole, rat, real, complex$ are groups over addition of number.
- $rat - {0}, real - {0}, rat^+, real^+, {+1, -1}, complex - {0}, {z in complex : |z| = 1}, {pm 1, pm i}$ are groups over multiplication.

== Dihedral Groups

#def(title: "Modulo arithmetic", [
  Let $a, b in whole_n$
  $
  a +_n b = cases(a + b & a + b < n, a + b - n quad & a + b >= n) \
  a times_n b = cases(0 & b = 0, a +_n a times (b - 1) quad &b > 0)
  $
])

The *dihedral groups* $D_n$ is the family of symmetry groups formed by regular $n$-gons.

$
    r^a r^b &= r^k \ 
    r^a (r^b s) &= r^k \
    (r^a s) r^b &= r^l s \
    (r^a s) (r^b s) &= r^l
$
where $k = a +_n b$ and $l = a +_n (n - b)$

== Subgroups and Generators

#def(title: "Subgroup", [
  $H < G$ if $H subset.eq G$ and $H$ is a group.
])

#def(title: "Cyclic group", [
  If all elements in $H$ can be written as $x^m$ where $x in G$, then $H$ is a cyclic group, that is the *subgroup generated by $x$*.

  $
  G="<"x">"
  $

  - If $G$ has order $n$, then $x^n = e$.
  - $nat = "<"1">"$ with infinite order.
])

Let $X = {x_1, x_2, dots, x_k$}, then $x_1^(m_1) x_2^(m_2)dots x_k^(m_k)$ is a word. Let $H$ be the set of all words, $H$ is called the subgroup generated by $X$.
- Translate by 1 $t space (+1)$ and reflect about 0 $s space (-x)$ generates the *infinite dihedral group* $D_infty = "<"s, t">"$

=== Theorem 5.1: one step subgroup test

Let $H$ be a non-empty subgroup of $G$.
$
H < G iff (x, y in H imp x y^(-1) in H)
$

=== Theorem 5.2: interseciton of subgroups

Let $H < G$ and $K < G$.
$
H inter K < G
$

=== Theorem 5.3: 

1. Every subgroup of $whole$ is cyclic.
2. Every subgroup of a cyclic group is cyclic.

== Permutations

#def(title: "Permutation", [
  A permutation is a bijection $alpha : X mapsto X$.
])

- $S_X$ is the set of all permutations from $X$ to $X$.
- $S_X$ is a group under function composition.
- $S_n = S_X$ where $X = {1, 2, dots, n}$
- The order of $S_n$ is $n!$

#def(title: "Cyclic permutation", [
  A cyclic permutation $(a b c d dots z)$ sends $a to b$, $b to c$, etc, and $z to a$.
  - A cyclic permutation of length $k$ is called a $k$-cycle.
  - A 2-cycle is called a *transposition*.
])

=== Theorem 6.1: transposition in $S_n$ generates $S_n$

$
(a_1 a_2 dots a_k) = (a_1a_k) dots (a_1a_3)(a_1a_2)
$

=== Theorem 6.2: more transpositions generates $S_n$

1. $(12),(13),dots,(1n)$ generates $S_n$
  $
  (a b) = (1a)(1b)(1a)
  $
2. $(12),(23), dots, (n-1 space n)$ generates $S_n$
  $
  (1k) = (k - 1 space k)dots(23)(12)(23)dots(k - 1 space k)
  $

=== Theorem 6.3: cyclic permutation generates $S_n$

$(12)$ and $(123 dots n)$ generates $S_n$
$
(k space k + 1) = (123 dots n)(12)(123 dots n)^(1 - k)
$

=== Theorem 6.4: even permutations

#def(title: "Even transpositions", [
  Even transpositions can be written as the composition of an even number of transpositions.
])

The even permutations in $S_n$ forms a subgroup of order $n! slash 2$ called $A_n$

=== Theorem 6.5: 3-cycles generates $A_n$

For $n >= 3$, the 3-cycles generates $A_n$

== Isomorphism

#def(title: "Isomorphism", [
  $G$ and $G'$ are isomorphic if there is a bijection $phi : G mapsto G'$ which satisfies $phi(x y) = phi(x)phi(y)$.
])

- $phi(x^(-1)) = phi(x)^(-1)$
- $phi(e) = e'$
- $G "albelian" imp x'y' = y'x'$

=== Plato's Solids

- The tetrahedron is isomorphic to $A_4$
- The cube and octahedron is isomorphic to $S_4$
- The dodecahedron and icosahedron is isomorphic to $A_5$

=== Theorem 8.1: Cayley's Theorem

Let $G$ be a group, then $G$ is isomorphic to a subgroup of $S_G$

=== Theorem 8.2: Cayley's with integer permutations

Let $G$ be a group, then $G$ is isomorphic to a subgroup of $S_(|G|)$

== Matrix Groups

Let $f_A (bold(x)) = bold(x) A^t$ such that it is a group under function composition: $f_(A B) (x) = x (A B)^t = x B^t A^t$ (notice $B$ is applied first).

#def(title: "General Linear Group", [
  $G L_n(T)$ is the set of all $n times n$ matrices such that $f_A: T^n mapsto T^n$ is invertible.
])

E.g. $G L_n (real)$ and $G L_n (complex)$

- Orthogonal matrices satisfies $A^t A = I$ where $A in G L_n(real)$ (the dot product of column $m$ and $n$ is 1 if $m=n$, 0 otherwise).
- $O_n$ is the set of all orthogonal matrices in $G L_n (real)$, $|A| = +1 "or" -1$
- $S O_n$ is the set of all orthogonal matrices where $|A| = +1$ only.

Orthogonal matricies preserves length and angles.

- Orthogonal matrices in complex numbers satisfies $A^(*t)A = I$, this is because the distance between two points in complex number is given by $z^*z$.
- $U_n$ is the set of all orthogonal matrices in $G L_n (complex)$
- $S U_n$ is the set of all orthogonal matrices where $|A| = +1$

== Products

#def(title: "Direct product", [
  The *direct product* $G times H$ is $(g, h)$, with multiplication $(g, h)(g', h') = (g g', h h')$
])

=== Theorem 10.1: Cyclic direct product

$
whole_m times whole_n "cyclic" iff gcd(m, n) = 1
$
Then $whole_m times whole_n = "<"(1, 1)">"$

=== Theorem 10.2: Subgroup isomorphic

Let $H < G$, $K < G$, $H K = G$, $H inter K = {e}$, every $h in H$ commutes with $g in G$, then
$
H times K iso G
$

=== Theorem 11.1: Legrange's theorem

The order of a subgroup of a finite group is always a divisor of the order of the group.


==== Corollaries

1. The order of every $g in G$ is a divisor of $|G|$
2. If $|G|$ is prime, then $G$ is cyclic.
3. If $x in G$ then $x^(|G|) = e$

#def(title: $R_n$, [
  - Let $R_n$ be the set of all $x in whole_n$ where $gcd(x, n) = 1$
  - Let $phi(n) = |R_n|$
])

=== Theorem 11.5: Euler's theorem

$
gcd(x, n) = 1 imp cong(x^(phi(n)), 1, n)
$

=== Theorem 11.6: Fermat's little theorem

If $p$ prime and $x$ is not a multiple of $p$, then
$
cong(x^(p-1), 1, p)
$
