#import "@local/lecture:0.1.0" : *

#set page(
  numbering: "1",
  supplement: [p.],
  number-align: right,
  header: [
    #set text(8pt)
    #smallcaps[Self Reading Notes]
    #h(1fr) _Groups and Symmetry (M. A. Armstrong)_
  ],
)

= Groups and Symmetry

#def(title: "Group", [
  A group $(G, binop)$ where $G$ is a set and $binop$ satisfies
  1. Associative, $(x binop y) binop z = x binop (y binop z)$
  2. Identity, there exist an $e in G$ where $x e = x = e x$
  3. Inverse, each element $x$ has an inverse, $x x^(-1) = e = x^(-1) x$

  A group is *abelian* if $binop$ is commutative.
])

- $whole, rat, real, complex$ are groups over addition of number.
- $rat - {0}, real - {0}, rat^+, real^+, {+1, -1}, complex - {0}, {z in complex : |z| = 1}, {pm 1, pm i}$ are groups over multiplication.

== Dihedral Groups

#def(title: "Modulo arithmetic", [
  Let $a, b in whole_n$
  $
  a +_n b = cases(a + b & a + b < n, a + b - n quad & a + b >= n) \
  a times_n b = cases(0 & b = 0, a +_n a times (b - 1) quad &b > 0)
  $
])

The *dihedral groups* $D_n$ is the family of symmetry groups formed by regular $n$-gons.

$
    r^a r^b &= r^k \ 
    r^a (r^b s) &= r^k \
    (r^a s) r^b &= r^l s \
    (r^a s) (r^b s) &= r^l
$
where $k = a +_n b$ and $l = a +_n (n - b)$

== Subgroups and Generators

#def(title: "Subgroup", [
  $H < G$ if $H subset.eq G$ and $H$ is a group.
])

#def(title: "Cyclic group", [
  If all elements in $H$ can be written as $x^m$ where $x in G$, then $H$ is a cyclic group, that is the *subgroup generated by $x$*.

  $
  G="<"x">"
  $

  - If $G$ has order $n$, then $x^n = e$.
  - $nat = "<"1">"$ with infinite order.
])

Let $X = {x_1, x_2, dots, x_k$}, then $x_1^(m_1) x_2^(m_2)dots x_k^(m_k)$ is a word. Let $H$ be the set of all words, $H$ is called the subgroup generated by $X$.
- Translate by 1 $t space (+1)$ and reflect about 0 $s space (-x)$ generates the *infinite dihedral group* $D_infty = "<"s, t">"$

=== Theorem 5.1: one step subgroup test

Let $H$ be a non-empty subgroup of $G$.
$
H < G iff (x, y in H imp x y^(-1) in H)
$

=== Theorem 5.2: interseciton of subgroups

Let $H < G$ and $K < G$.
$
H inter K < G
$

=== Theorem 5.3: 

1. Every subgroup of $whole$ is cyclic.
2. Every subgroup of a cyclic group is cyclic.

== Permutations

#def(title: "Permutation", [
  A permutation is a bijection $alpha : X mapsto X$.
])

- $S_X$ is the set of all permutations from $X$ to $X$.
- $S_X$ is a group under function composition.
- $S_n = S_X$ where $X = {1, 2, dots, n}$
- The order of $S_n$ is $n!$

#def(title: "Cyclic permutation", [
  A cyclic permutation $(a b c d dots z)$ sends $a to b$, $b to c$, etc, and $z to a$.
  - A cyclic permutation of length $k$ is called a $k$-cycle.
  - A 2-cycle is called a *transposition*.
])

=== Theorem 6.1: transposition in $S_n$ generates $S_n$

$
(a_1 a_2 dots a_k) = (a_1a_k) dots (a_1a_3)(a_1a_2)
$

=== Theorem 6.2: more transpositions generates $S_n$

1. $(12),(13),dots,(1n)$ generates $S_n$
  $
  (a b) = (1a)(1b)(1a)
  $
2. $(12),(23), dots, (n-1 space n)$ generates $S_n$
  $
  (1k) = (k - 1 space k)dots(23)(12)(23)dots(k - 1 space k)
  $

=== Theorem 6.3: cyclic permutation generates $S_n$

$(12)$ and $(123 dots n)$ generates $S_n$
$
(k space k + 1) = (123 dots n)(12)(123 dots n)^(1 - k)
$

=== Theorem 6.4: even permutations

#def(title: "Even transpositions", [
  Even transpositions can be written as the composition of an even number of transpositions.
])

The even permutations in $S_n$ forms a subgroup of order $n! slash 2$ called $A_n$

=== Theorem 6.5: 3-cycles generates $A_n$

For $n >= 3$, the 3-cycles generates $A_n$
